civis-vote/civis-api

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/graphql/types/objects/consultation/base.rb, app/graphql/types/objects/consultation_response/base.rb, app/models/consultation_response.rb, app/models/user.rb, app/views/admin/users/show.html.slim, db/migrate/20190906150652_add_reading_time_to_consultation_responses.rb, db/migrate/20190909111050_change_reading_time_to_consultation_responses.rb, db/schema.rb
Added moderator role in user and changed the conditions to allow modertor to access admin panel
=> feat: Added reading time for responses in consultation responses

Gemfile, Gemfile.lock, config/schedule.rb, config/sitemap.rb
* chore(deps): bump rack-cors from 1.0.3 to 1.0.5
Bumps [rack-cors](https://github.com/cyu/rack-cors) from 1.0.3 to 1.0.5.
- [Release notes](https://github.com/cyu/rack-cors/releases)
- [Changelog](https://github.com/cyu/rack-cors/blob/master/CHANGELOG.md)
- [Commits](https://github.com/cyu/rack-cors/compare/v1.0.3...v1.0.5)
Signed-off-by: dependabot[bot] <support@github.com>
* feat: sitemap added and uploaded to google-cloud-storage
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: BALAJI-BALA <balaji.d.94.it@gmail.com>
=> feat: Sitemap Generator (#223)

db/migrate/20200110062155_remove_response_text_from_consultation_response.rb, db/schema.rb
=> improvements: removed unwanted fields from the consultation and consultation_response models

app/models/concerns/image_resizer.rb, config/initializers/shrine.rb, db/migrate/20200331122626_add_logo_versions_data_to_ministry.rb, db/schema.rb
This for retrieving resized image url using their exact resolution, because shrine every time upload and retrieves the url and not saving in any column, this is taking so much longer time to load in the front end.
=> feat: Added a new column to save resized image url to jsonb

app/controllers/organisation/consultations_controller.rb, app/graphql/mutations/auth/accept_invite.rb, app/graphql/types/inputs/auth/accept_invite.rb, app/graphql/types/mutation_type.rb, app/models/respondent.rb
@mikevic Bro ChangeLog [Link](https://staging.changelog.commutatus.com/companies/civis/projects/api-3c218b6f-4ed5-4ec2-a371-3ca5f9655fca/respondent-user-flow)
=> feat: Added new respondent invite flow and mutuation to accept invite

app/controllers/admin/consultations_controller.rb, app/controllers/organisation/consultations_controller.rb, app/javascript/application/coffee_scripts/consultations.coffee, app/javascript/application/stylesheets/admin_panel.css.scss, app/models/concerns/import_response.rb, app/views/admin/consultations/show.html.slim, app/views/organisation/consultations/show.html.slim, config/routes.rb
- Added response import feature to organisations.
- Added condition to rescue if there is no questions found from the sheet.
- Added mini loader when uploading file
- Replaced template sample URL
- changed condition in file import to check for the user present to associate user_id to Consultation Response
=> improvements: civis import feature to handle if no survey questions on sheet

app/mailers/user_mailer.rb, app/models/concerns/import_response.rb, app/views/admin/consultations/show.html.slim, app/views/organisation/consultations/show.html.slim
* improvements: modified the code to accept response for the questions and answers from string
* improvements: allowed multiple option from checkbox question type in response import
=> Staging <- Develop ( improvements: allowed multiple option from checkbox question type in response import (#594) )

config/application.rb, config/initializers/content_security_policy.rb
Reverts civis-vote/civis-api#665
=> Revert "develop"

.travis.yml
=> :bug: : update ruby version in travis config file (#CIV-606)

package.json, yarn.lock
included updated package json config
=> :bug: : include updated package json files (#CIV-606)

.travis.yml, package.json, yarn.lock
included updated package json config
=> 🐛 : include updated package json files (#CIV-606)

package.json, yarn.lock
=> 🐛 : update yarn lock for compatible node (#CIV-606)

package.json, yarn.lock
=> change yarn lock config file

Gemfile, Gemfile.lock
=> 🐛 : additional gem to resolve worker error (#CIV-606)

.travis.yml, Gemfile, Gemfile.lock
Downgrading ruby version 3.1.0 to 3.0.0
3.1.0 not stable in the staging environment
=> :arrow_down: : downgrade ruby version to 3.0.0 (#CIV-606)

.travis.yml, Gemfile, Gemfile.lock
Downgrading ruby version 3.1.0 to 3.0.0
3.1.0 not stable in the staging environment
=> Downgrade to 3.0.0

config/initializers/omniauth.rb
[CIV-622](https://commutatus.atlassian.net/browse/CIV-622)
issue with latest omniauth gem
since we are redirecting from controller the post action is not calling 
and in the latest gem its throws error
=> :bug: google outh error in gem (#CIV-622)

.cloud66/manifest.yml.yml
…move validations
[CIV-633](https://commutatus.atlassian.net/browse/CIV-633)
migrating to aws rds from cloud 66
=> CIV-633 : attaching manifest.yml file

.cloud66/deploy_hooks.yml, config/database.yml.cloud66
…move validations
[CIV-633](https://commutatus.atlassian.net/browse/CIV-633)
migrating to aws rds from cloud 66
added codes to copy database.yml configs to cloud 66 server
=> CIV-633 : :zap: : code for copying the config for database.yml

app/mailers/user_mailer.rb, app/models/consultation.rb
[CIV-641](https://commutatus.atlassian.net/browse/CIV-641)
english summary is not showing in export file
the summary showing in the show page and the summary fetching in export file are different
=> CIV-641 :bug: : english summary not recieving in consultation export

app/models/consultation.rb
[CIV-641](https://commutatus.atlassian.net/browse/CIV-641)
english summary is not showing in export file
the summary showing in the show page and the summary fetching in export file are different
=> CIV-641 : :bug: : return summary if summary present

config/initializers/content_security_policy.rb
commenting content security policy
=> :hammer: commenting content security policy

app/models/consultation.rb
commenting content security policy
=> Civ 641 master

app/mailers/user_mailer.rb, lib/tasks/send_consultation_responses.rake
[CIV-637](https://commutatus.atlassian.net/browse/CIV-637)
task to send all user responses in a single file export
=> CIV-637: :sparkles:: task to export all subjective responses

app/mailers/user_mailer.rb
[CIV-637](https://commutatus.atlassian.net/browse/CIV-637)
task to send all user responses in a single file export
allocate all long text responses
=> CIV-637 : :hammer: :refactor code to include all long text responses

config/routes.rb
adding authorization for sidekiq
added uniq validation for order code, included order change code while changing branch
=> CIV-678 : :art: : adding authorization to sidekiq

Gemfile, Gemfile.lock, README.md, db/seeds.rb, spec/fabricators/category_fabricator.rb, spec/fabricators/consultation_fabricator.rb, spec/fabricators/consultation_response_fabricator.rb, spec/fabricators/ministry.rb, spec/fabricators/user_fabricator.rb, spec/fabricators/wordindex_fabricator.rb
New developers find difficult to work in Civis due to old seed files 
refactored seed files, fabricators
updated readme files
=> CIV-679 :books: updating seed file and readme document

app/graphql/types/objects/api_key.rb
adding a new field in the apikey object receiving in the mutation
issue with FE due to sending some queries using localstorage data
=> CIV-699 :bug: adding expires_at response in ApiKey object

app/graphql/queries/consultation/profile.rb
=> [staging] Change in private consultation flow

app/jobs/notify_expired_consultation_email_job.rb, app/mailers/user_mailer.rb, app/models/consultation.rb, app/views/admin/ministries/_form.html.slim
=> [staging] Changes to feedback report email 

app/jobs/notify_pending_review_of_profane_responses_email_to_admin_job.rb
=> [staging] Update triggers and set up daily reports on pending responses

app/controllers/admin/consultations_controller.rb, app/jobs/consultation_feedback_report_email_job.rb, app/jobs/notify_pending_review_of_profane_responses_email_to_admin_job.rb, app/jobs/use_response_as_template_email_job.rb, app/jobs/user_up_vote_responses_email_job.rb, app/mailers/user_mailer.rb, app/models/consultation.rb, app/views/admin/consultations/_form.html.slim, app/views/admin/consultations/show.html.slim, config/schedule.rb, db/migrate/20230925125754_add_officer_name_and_designation_to_consultation.rb, db/schema.rb, lib/tasks/email_pending_review_response.rake
=> [staging] Officer name & designation on consultation show page

app/views/admin/consultations/show.html.slim
- Officer name & designation on the consultation show page.
- Indentation fix and remove trailing spaces.
=> Officer name & designation on consultation show page

app/graphql/mutations/auth/accept_invite.rb, app/models/user.rb, app/views/organisation/consultations/show.html.slim
=> [staging] Change invitation expiry condition based on response deadline

app/graphql/mutations/auth/accept_invite.rb, app/graphql/mutations/auth/reset_password.rb, config/initializers/devise.rb, config/locales/en.yml
=> [Staging] Reset password error message and token interval improvement

app/graphql/mutations/auth/reset_password.rb, app/graphql/mutations/consultation_response/create.rb, config/initializers/devise.rb, config/locales/en.yml
=> [Staging] Bypass authentication for response submission

app/graphql/mutations/consultation_response/create.rb, config/locales/en.yml
=> [Staging] Fix the condition for environment check

app/graphql/mutations/consultation_response/create.rb
Fix the condition for environment check
=> Fix the condition for environment check

config/initializers/sentry.rb
=> [Staging] fix: remove http breadcumb for staging testing

config/initializers/sentry.rb
=> [Staging] fix: remove breadcumb for staging testign

db/seeds.rb, lib/tasks/convert_page_to_action_text.rake
=> [Staging] Chore: create rake task for migration to action text #864

.cloud66/deploy_hooks.yml, app/assets/stylesheets/application.scss
=> [Staging] fix: added libvips package for servers

.cloud66/manifest.yml
=> [Staging] fix: update ubuntu version

.cloud66/manifest.yml
=> [Staging] chore: add postgresql version in cloud66 manifest

app/mailers/user_mailer.rb
- added extra field in exported file for 'Consultation Page Link'
- requested by client.
- edited method `consultation_export_email_job` in `user_mailer.rb` to have extra field key and value.
=> chore: add consultation page link on exported files

app/models/consultation.rb, db/seeds.rb, lib/tasks/convert_page_to_action_text.rake
- created a rake task to migrate from page builder to action text
- required to migrate data for rails 7 upgrade
- created a rake task.
- updated summaries with page component data.
- I manually tested all the operations locally.
=> Chore: create rake task for migration to action text

db/migrate/20240517045437_change_s3_image_urls.rb, db/schema.rb
- update old s3 image url to not use tokens
=> fix: update old s3 image urls

app/controllers/oauth_controller.rb, db/migrate/20240517045437_change_s3_image_urls.rb, db/schema.rb
=> [Staging] Fix for oauth redirection fail

app/graphql/mutations/current_user/update.rb
=> [Staging] fix: change to use update method

app/models/consultation.rb
=> [Staging] Expiry job fix

app/views/admin/consultations/show.html.slim, app/views/organisation/consultations/show.html.slim, db/seeds.rb, spec/fabricators/ministry.rb
Changes Made:
Showcase question ID against the questions in the consultation details page
Added A Mandatory Tag to Questions Section
Changes in seeds for intialization
Changes in spec file for intialization
=> [staging] Showcase question ID against the questions in the consultation details page

app/views/admin/organisations/_table.html.slim, app/views/admin/organisations/show.html.slim
Changes Made:
Added ID to Organization Details 
Added ID to Organization Index
=> [staging] Added ID on list page and index in organisation section

app/views/admin/organisations/_table.html.slim, app/views/admin/organisations/show.html.slim
**Changes Made:**
- Added ID to Organization Details
- Added ID to Organization Index
=> feat: Pro 5521- Showcase organisation ID on list page

app/views/admin/consultations/show.html.slim, app/views/organisation/consultations/show.html.slim, db/seeds.rb, spec/fabricators/ministry.rb
**Changes Made:**
1. Showcase question ID against the questions in the consultation details page
2. Added A Mandatory Tag to Questions Section
3. Changes in seeds for intialization
4. Changes in spec file for intialization
=> feat:5520- Showcase question ID against the questions in the consultation details

app/javascript/custom/consultations.js, app/views/admin/questions/_edit_questions.html.slim, app/views/organisation/questions/_edit_questions.html.slim
=> Fix:Pro 6035: Validation Fix

app/views/admin/questions/_edit_questions.html.slim, app/views/organisation/questions/_edit_questions.html.slim
=> Fix:Fix UI

app/javascript/custom/consultations.js
- Fix for consultation question delete
=> Fix:PRO-6035:Some fixes delete in consultaion question options

app/controllers/admin/consultations_controller.rb, config/routes.rb
-Odia Summary Fix in Admin controller
=> fix:Pro 6035: Odia Summary Fix in Admin controller 

.github/CODEOWNERS
=> CI:add codeowners to civis

app/graphql/types/objects/consultation_partner_response/list.rb
=> Fix:PRO-5943:Fix for graphql type consultaion partner

app/views/admin/consultations/show.html.slim
- Removed extra deadline field in consultation show
=> Feat:PRO-6119:Removed extra deadline field in consultation show

app/graphql/types/objects/consultation/base.rb
- Updated to Dynamic Response count
=> [staging] Feat:Updated to Dynamic Response count 

app/graphql/types/objects/consultation/base.rb
- Updated to Dynamic Response count
=> Feat:Updated to Dynamic Response count 

app/mailers/user_mailer.rb
- Updated Response count in User Mailer
=> [staging] Fix:Updated Response count in User Mailer

app/mailers/user_mailer.rb
Reverts civis-vote/civis-api#930
=> Revert "[staging] Fix:Updated Response count in User Mailer"

app/controllers/admin/consultations_controller.rb, app/mailers/user_mailer.rb, config/routes.rb, db/migrate/20241113111003_add_feedback_email_details.rb, db/migrate/20241118094017_add_clicked_at_to_consultations.rb, db/schema.rb
add feedback email timestamps to consultations
=> feat: add feedback email timestamps to consultations

app/graphql/mutations/consultation_response/create.rb
- Added Skip Authorization to Consultation for 1089
=> [staging] Feat: Added Skip Authorization to Consultation for 1089

app/graphql/mutations/consultation_response/create.rb
- Added Skip Authorization to Consultation for 1089
=> Feat: Added Skip Authorization to Consultation for 1089

app/controllers/admin/consultations_controller.rb, app/controllers/organisation/consultations_controller.rb, app/graphql/types/objects/consultation/base.rb, app/views/admin/consultations/_form.html.slim, app/views/admin/consultations/show.html.slim, app/views/organisation/consultations/show.html.slim, db/migrate/20250428142232_show_discuss_engage_tab.rb, db/migrate/20250428153237_change_to_show_discuss_section.rb, db/schema.rb
Added Allow discuss engage tab
=> Feat:PRO-9611: Added Allow discuss engage tab

app/graphql/mutations/consultation_response/create.rb, app/models/consultation.rb
- Added Skip Authorization to Consultation for 1245 for production and 475 for staging
#Previous PR:- [#959 Feat: Added Skip Authorization to Consultation for 1089](https://github.com/civis-vote/civis-api/pull/959)
=> Feat: Added Skip Authorization to Consultation for 1245

app/models/concerns/cm_admin/consultation.rb, app/models/concerns/cm_admin/respondent.rb, app/models/consultation.rb, app/models/respondent.rb, app/models/user.rb, config/initializers/zcm_admin.rb
https://commutatus.slack.com/archives/CJRJ7RM98/p1756107444577889
=> feat: add respondent invitation functionality for private consultations with CM Admin integration
